apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: marco
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: front-deployment
      app.kubernetes.io/component: front
      app.kubernetes.io/part-of: marco
  template:
    metadata:
      labels:
        app.kubernetes.io/name: front-deployment
        app.kubernetes.io/component: front
        app.kubernetes.io/part-of: marco
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        supplementalGroups:
        - 3300
      imagePullSecrets:
        - name: regcred

      containers:
        - name: front-deployment
          image: 282943519253.dkr.ecr.us-east-1.amazonaws.com/comercial-frontend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: api-conf
            - secretRef:
                name: api-secrets
          resources:
            limits:
              memory: 512M
              cpu: 400m
            requests:
              memory: 256M
              cpu: 200m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          ports:
            - containerPort: 8080
