apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apishareholders
  namespace: marco
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399, 404"
  labels:
    name: apishareholders-service
spec:
  tls:
  - hosts:
    - "#{{SpecTlsHostApiShareholders}}#"
    secretName: sitec-generic
  rules:
  - host: "#{{SpecTlsHostApiShareholders}}#"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: apishareholders-service
            port: 
              number: 8080 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontshareholders
  namespace: marco
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399, 404"
  labels:
    name: frontshareholders-service
spec:
  tls:
  - hosts:
    - "#{{SpecTlsHostFrontShareholders}}#"
    secretName: sitec-generic
  rules:
  - host: "#{{SpecTlsHostFrontShareholders}}#"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontshareholders-service
            port: 
              number: 80 