apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apishareholders-scaler
  namespace: marco
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apishareholders-deployment  
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontshareholders-scaler
  namespace: marco
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontshareholders-deployment  
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70