apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: marco
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: api-deployment
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: marco
  ports:
  - targetPort: 80
    #puerto de la imagen
    port: 80
    #puerto de servicio
    nodePort: 30010
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: marco
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: front-deployment
    app.kubernetes.io/component: front
    app.kubernetes.io/part-of: marco
  ports:
  - targetPort: 80
    #puerto de la imagen
    port: 80
    #puerto de servicio
    nodePort: 30020